const DATA = [
  {
    id_number: 1,
    firstName: "Karine",
    lastName: "Paskins",
    email: "kpaskins0@squarespace.com",
    phone: "940-398-4619",
  },
  {
    id_number: 2,
    firstName: "Teodoor",
    lastName: "Udey",
    email: "tudey1@de.vu",
    phone: "624-683-2919",
  },
  {
    id_number: 3,
    firstName: "Floyd",
    lastName: "Brumbye",
    email: "fbrumbye2@slideshare.net",
    phone: "376-375-3789",
  },
  {
    id_number: 4,
    firstName: "Alasdair",
    lastName: "Stimpson",
    email: "astimpson3@google.co.uk",
    phone: "590-430-5596",
  },
  {
    id_number: 5,
    firstName: "Helli",
    lastName: "Deakin",
    email: "hdeakin4@opensource.org",
    phone: "631-541-9543",
  },
  {
    id_number: 6,
    firstName: "Christophorus",
    lastName: "Ginie",
    email: "cginie5@columbia.edu",
    phone: "516-212-0503",
  },
  {
    id_number: 7,
    firstName: "Rafaello",
    lastName: "Curds",
    email: "rcurds6@cnn.com",
    phone: "635-945-7594",
  },
  {
    id_number: 8,
    firstName: "Darla",
    lastName: "Parkyn",
    email: "dparkyn7@pbs.org",
    phone: "739-693-5308",
  },
  {
    id_number: 9,
    firstName: "Pren",
    lastName: "Donativo",
    email: "pdonativo8@privacy.gov.au",
    phone: "581-460-8134",
  },
  {
    id_number: 10,
    firstName: "Kippie",
    lastName: "Parry",
    email: "kparry9@apache.org",
    phone: "265-240-7082",
  },
  {
    id_number: 11,
    firstName: "Ulrick",
    lastName: "Meredyth",
    email: "umeredytha@linkedin.com",
    phone: "457-905-2696",
  },
  {
    id_number: 12,
    firstName: "Sylvester",
    lastName: "Alcide",
    email: "salcideb@archive.org",
    phone: "254-408-7139",
  },
  {
    id_number: 13,
    firstName: "Jacquelynn",
    lastName: "Ramas",
    email: "jramasc@un.org",
    phone: "725-734-2877",
  },
  {
    id_number: 14,
    firstName: "Colette",
    lastName: "Grundy",
    email: "cgrundyd@yale.edu",
    phone: "287-963-2088",
  },
  {
    id_number: 15,
    firstName: "Alick",
    lastName: "Burstow",
    email: "aburstowe@lulu.com",
    phone: "430-419-1334",
  },
  {
    id_number: 16,
    firstName: "Harley",
    lastName: "Attwooll",
    email: "hattwoollf@livejournal.com",
    phone: "766-971-2234",
  },
  {
    id_number: 17,
    firstName: "Rocky",
    lastName: "Rixon",
    email: "rrixong@disqus.com",
    phone: "642-795-6596",
  },
  {
    id_number: 18,
    firstName: "Nancie",
    lastName: "Wroath",
    email: "nwroathh@cbslocal.com",
    phone: "820-470-1386",
  },
  {
    id_number: 19,
    firstName: "Irv",
    lastName: "Zellmer",
    email: "izellmeri@php.net",
    phone: "148-371-6825",
  },
  {
    id_number: 20,
    firstName: "Noelle",
    lastName: "Saville",
    email: "nsavillej@domainmarket.com",
    phone: "186-132-0784",
  },
  {
    id_number: 21,
    firstName: "Myles",
    lastName: "Rasp",
    email: "mraspk@jalbum.net",
    phone: "376-507-8605",
  },
  {
    id_number: 22,
    firstName: "Ikey",
    lastName: "Frie",
    email: "ifriel@yahoo.com",
    phone: "659-958-4621",
  },
  {
    id_number: 23,
    firstName: "Wenda",
    lastName: "Lightowlers",
    email: "wlightowlersm@fotki.com",
    phone: "453-711-2429",
  },
  {
    id_number: 24,
    firstName: "Aili",
    lastName: "Rugge",
    email: "aruggen@blogs.com",
    phone: "734-135-2283",
  },
  {
    id_number: 25,
    firstName: "Ambros",
    lastName: "de Glanville",
    email: "adeglanvilleo@google.cn",
    phone: "270-879-3271",
  },
  {
    id_number: 26,
    firstName: "Louie",
    lastName: "Aupol",
    email: "laupolp@51.la",
    phone: "647-457-3969",
  },
  {
    id_number: 27,
    firstName: "Chaim",
    lastName: "Petrosian",
    email: "cpetrosianq@nyu.edu",
    phone: "999-752-8448",
  },
  {
    id_number: 28,
    firstName: "Gypsy",
    lastName: "Glennie",
    email: "gglennier@issuu.com",
    phone: "173-147-4311",
  },
  {
    id_number: 29,
    firstName: "Garner",
    lastName: "Hudghton",
    email: "ghudghtons@i2i.jp",
    phone: "299-522-6908",
  },
  {
    id_number: 30,
    firstName: "Kristopher",
    lastName: "Godbald",
    email: "kgodbaldt@microsoft.com",
    phone: "204-206-2412",
  },
  {
    id_number: 31,
    firstName: "Trumann",
    lastName: "Denisyuk",
    email: "tdenisyuku@google.nl",
    phone: "637-749-6768",
  },
  {
    id_number: 32,
    firstName: "Ainslee",
    lastName: "Cromblehome",
    email: "acromblehomev@yahoo.co.jp",
    phone: "487-478-4204",
  },
  {
    id_number: 33,
    firstName: "Willa",
    lastName: "Chesworth",
    email: "wchesworthw@google.cn",
    phone: "984-936-3320",
  },
  {
    id_number: 34,
    firstName: "Goran",
    lastName: "Romand",
    email: "gromandx@ucsd.edu",
    phone: "377-742-6233",
  },
  {
    id_number: 35,
    firstName: "Ann-marie",
    lastName: "Munsey",
    email: "amunseyy@cornell.edu",
    phone: "640-904-1709",
  },
  {
    id_number: 36,
    firstName: "Orren",
    lastName: "Leverett",
    email: "oleverettz@oakley.com",
    phone: "441-630-7721",
  },
  {
    id_number: 37,
    firstName: "Reginald",
    lastName: "Duley",
    email: "rduley10@pen.io",
    phone: "526-346-9296",
  },
  {
    id_number: 38,
    firstName: "Kelsey",
    lastName: "Ciccottio",
    email: "kciccottio11@123-reg.co.uk",
    phone: "824-627-0061",
  },
  {
    id_number: 39,
    firstName: "Stanislaw",
    lastName: "Cage",
    email: "scage12@microsoft.com",
    phone: "907-424-5473",
  },
  {
    id_number: 40,
    firstName: "Nerita",
    lastName: "Loxston",
    email: "nloxston13@discuz.net",
    phone: "170-559-2874",
  },
  {
    id_number: 41,
    firstName: "Mimi",
    lastName: "Bellew",
    email: "mbellew14@time.com",
    phone: "221-475-8716",
  },
  {
    id_number: 42,
    firstName: "Rodney",
    lastName: "Grand",
    email: "rgrand15@oracle.com",
    phone: "674-391-9556",
  },
  {
    id_number: 43,
    firstName: "Omero",
    lastName: "Lorans",
    email: "olorans16@whitehouse.gov",
    phone: "160-622-6365",
  },
  {
    id_number: 44,
    firstName: "Julissa",
    lastName: "Karczinski",
    email: "jkarczinski17@ehow.com",
    phone: "800-942-2537",
  },
  {
    id_number: 45,
    firstName: "Genia",
    lastName: "Midgley",
    email: "gmidgley18@google.cn",
    phone: "615-865-6783",
  },
  {
    id_number: 46,
    firstName: "Burt",
    lastName: "Hulland",
    email: "bhulland19@bloomberg.com",
    phone: "749-987-3406",
  },
  {
    id_number: 47,
    firstName: "Conney",
    lastName: "Dust",
    email: "cdust1a@zdnet.com",
    phone: "798-336-3779",
  },
  {
    id_number: 48,
    firstName: "Ernesta",
    lastName: "Steen",
    email: "esteen1b@yahoo.com",
    phone: "641-334-4741",
  },
  {
    id_number: 49,
    firstName: "Trula",
    lastName: "Balazin",
    email: "tbalazin1c@wp.com",
    phone: "529-561-7832",
  },
  {
    id_number: 50,
    firstName: "Debby",
    lastName: "Leggon",
    email: "dleggon1d@seattletimes.com",
    phone: "636-177-0519",
  },
  {
    id_number: 51,
    firstName: "Athena",
    lastName: "Harvett",
    email: "aharvett1e@icq.com",
    phone: "872-115-5635",
  },
  {
    id_number: 52,
    firstName: "Reggy",
    lastName: "Havoc",
    email: "rhavoc1f@ucsd.edu",
    phone: "543-835-2485",
  },
  {
    id_number: 53,
    firstName: "Nissa",
    lastName: "Giottini",
    email: "ngiottini1g@godaddy.com",
    phone: "322-153-2509",
  },
  {
    id_number: 54,
    firstName: "Micheline",
    lastName: "Boleyn",
    email: "mboleyn1h@salon.com",
    phone: "204-312-7473",
  },
  {
    id_number: 55,
    firstName: "Izabel",
    lastName: "Cains",
    email: "icains1i@blogger.com",
    phone: "994-626-2875",
  },
  {
    id_number: 56,
    firstName: "Robina",
    lastName: "Celle",
    email: "rcelle1j@gizmodo.com",
    phone: "995-203-8825",
  },
  {
    id_number: 57,
    firstName: "Madella",
    lastName: "Quest",
    email: "mquest1k@woothemes.com",
    phone: "619-672-2209",
  },
  {
    id_number: 58,
    firstName: "Fielding",
    lastName: "Moors",
    email: "fmoors1l@friendfeed.com",
    phone: "530-464-2547",
  },
  {
    id_number: 59,
    firstName: "Veriee",
    lastName: "Pilbeam",
    email: "vpilbeam1m@japanpost.jp",
    phone: "241-655-8475",
  },
  {
    id_number: 60,
    firstName: "Madeline",
    lastName: "Steet",
    email: "msteet1n@guardian.co.uk",
    phone: "984-993-0884",
  },
  {
    id_number: 61,
    firstName: "Porty",
    lastName: "O'Spellissey",
    email: "pospellissey1o@yolasite.com",
    phone: "204-947-3912",
  },
  {
    id_number: 62,
    firstName: "Saloma",
    lastName: "Camplin",
    email: "scamplin1p@patch.com",
    phone: "134-937-7489",
  },
  {
    id_number: 63,
    firstName: "Page",
    lastName: "Cuffin",
    email: "pcuffin1q@answers.com",
    phone: "343-287-0739",
  },
  {
    id_number: 64,
    firstName: "Trula",
    lastName: "Stillgoe",
    email: "tstillgoe1r@joomla.org",
    phone: "141-226-0058",
  },
  {
    id_number: 65,
    firstName: "Cullin",
    lastName: "Whitelock",
    email: "cwhitelock1s@squarespace.com",
    phone: "796-929-3945",
  },
  {
    id_number: 66,
    firstName: "Eugine",
    lastName: "Falk",
    email: "efalk1t@phpbb.com",
    phone: "977-937-0724",
  },
  {
    id_number: 67,
    firstName: "Bren",
    lastName: "Penkethman",
    email: "bpenkethman1u@ibm.com",
    phone: "325-832-6025",
  },
  {
    id_number: 68,
    firstName: "Ardeen",
    lastName: "Reynoollds",
    email: "areynoollds1v@yolasite.com",
    phone: "247-585-7518",
  },
  {
    id_number: 69,
    firstName: "Leelah",
    lastName: "Harkness",
    email: "lharkness1w@noaa.gov",
    phone: "243-315-5933",
  },
  {
    id_number: 70,
    firstName: "Priscella",
    lastName: "Norville",
    email: "pnorville1x@booking.com",
    phone: "650-862-2380",
  },
  {
    id_number: 71,
    firstName: "Andreana",
    lastName: "Tidgewell",
    email: "atidgewell1y@flavors.me",
    phone: "762-676-1433",
  },
  {
    id_number: 72,
    firstName: "Adelaide",
    lastName: "Van Saltsberg",
    email: "avansaltsberg1z@imageshack.us",
    phone: "998-941-2218",
  },
  {
    id_number: 73,
    firstName: "Hetty",
    lastName: "Fairbourn",
    email: "hfairbourn20@simplemachines.org",
    phone: "861-862-6421",
  },
  {
    id_number: 74,
    firstName: "Ediva",
    lastName: "Bulteel",
    email: "ebulteel21@skyrock.com",
    phone: "359-913-4341",
  },
  {
    id_number: 75,
    firstName: "Keelia",
    lastName: "Jaksic",
    email: "kjaksic22@dailymotion.com",
    phone: "245-412-3198",
  },
  {
    id_number: 76,
    firstName: "Adriane",
    lastName: "Spacie",
    email: "aspacie23@purevolume.com",
    phone: "354-857-0949",
  },
  {
    id_number: 77,
    firstName: "Maitilde",
    lastName: "Bardill",
    email: "mbardill24@sciencedaily.com",
    phone: "556-100-5169",
  },
  {
    id_number: 78,
    firstName: "Guillaume",
    lastName: "Corssen",
    email: "gcorssen25@netlog.com",
    phone: "488-268-7963",
  },
  {
    id_number: 79,
    firstName: "Natale",
    lastName: "Yeoland",
    email: "nyeoland26@bing.com",
    phone: "400-774-2931",
  },
  {
    id_number: 80,
    firstName: "Pru",
    lastName: "Avramchik",
    email: "pavramchik27@prweb.com",
    phone: "484-506-5973",
  },
  {
    id_number: 81,
    firstName: "Natasha",
    lastName: "Tomasian",
    email: "ntomasian28@wikimedia.org",
    phone: "866-403-4771",
  },
  {
    id_number: 82,
    firstName: "Gilbertina",
    lastName: "Gowen",
    email: "ggowen29@msu.edu",
    phone: "507-242-0919",
  },
  {
    id_number: 83,
    firstName: "Jenelle",
    lastName: "Heinonen",
    email: "jheinonen2a@geocities.jp",
    phone: "520-496-0252",
  },
  {
    id_number: 84,
    firstName: "Jasper",
    lastName: "Sparrowhawk",
    email: "jsparrowhawk2b@blogtalkradio.com",
    phone: "606-722-9969",
  },
  {
    id_number: 85,
    firstName: "Vikky",
    lastName: "Eller",
    email: "veller2c@examiner.com",
    phone: "302-782-7555",
  },
  {
    id_number: 86,
    firstName: "Heloise",
    lastName: "Carabine",
    email: "hcarabine2d@yelp.com",
    phone: "758-359-3874",
  },
  {
    id_number: 87,
    firstName: "Katlin",
    lastName: "Rudkin",
    email: "krudkin2e@umich.edu",
    phone: "950-707-5933",
  },
  {
    id_number: 88,
    firstName: "Wynne",
    lastName: "Ditty",
    email: "wditty2f@globo.com",
    phone: "216-807-2298",
  },
  {
    id_number: 89,
    firstName: "Ainslee",
    lastName: "Mayhead",
    email: "amayhead2g@aol.com",
    phone: "863-530-4407",
  },
  {
    id_number: 90,
    firstName: "Jaime",
    lastName: "Hick",
    email: "jhick2h@springer.com",
    phone: "222-132-0477",
  },
  {
    id_number: 91,
    firstName: "Kimberli",
    lastName: "O'Toole",
    email: "kotoole2i@diigo.com",
    phone: "897-221-2209",
  },
  {
    id_number: 92,
    firstName: "Briney",
    lastName: "Luddy",
    email: "bluddy2j@linkedin.com",
    phone: "827-572-3905",
  },
  {
    id_number: 93,
    firstName: "Sigismundo",
    lastName: "Sindle",
    email: "ssindle2k@miitbeian.gov.cn",
    phone: "579-855-4172",
  },
  {
    id_number: 94,
    firstName: "Myrtia",
    lastName: "Codeman",
    email: "mcodeman2l@umn.edu",
    phone: "195-729-0086",
  },
  {
    id_number: 95,
    firstName: "Rahal",
    lastName: "Jeanin",
    email: "rjeanin2m@wunderground.com",
    phone: "626-556-2577",
  },
  {
    id_number: 96,
    firstName: "Anthea",
    lastName: "Crannell",
    email: "acrannell2n@ovh.net",
    phone: "443-838-0722",
  },
  {
    id_number: 97,
    firstName: "Victoir",
    lastName: "Pynner",
    email: "vpynner2o@flavors.me",
    phone: "872-146-0067",
  },
  {
    id_number: 98,
    firstName: "Ketti",
    lastName: "Thinn",
    email: "kthinn2p@seesaa.net",
    phone: "759-174-6615",
  },
  {
    id_number: 99,
    firstName: "Samson",
    lastName: "Hogben",
    email: "shogben2q@cornell.edu",
    phone: "943-733-4104",
  },
  {
    id_number: 100,
    firstName: "Jaynell",
    lastName: "Queree",
    email: "jqueree2r@bing.com",
    phone: "937-531-0705",
  },
];

const paginate = (items, page = 1, perPage = 10) =>
  items.slice(perPage * (page - 1), perPage * page);

export default function fetchData(page) {
  return paginate(DATA, page, 10);
}
